from selenium.webdriver.common.by import By

class AuthorizationLocators:
    LOGIN_BUTTON = (By.XPATH, "//button[text()='Вход и регистрация']")
    LOGOUT_BUTTON = (By.XPATH, "//button[text()='Выйти']")
    NO_ACCOUNT_BUTTON = (By.XPATH, "//button[text()='Нет аккаунта']")
    CREATE_ACCOUNT_BUTTON = (By.XPATH, "//button[text()='Создать аккаунт']")
    MAIN_LOGIN_BUTTON = (By.XPATH, "//button[text()='Войти']")
    EMAIL_FIELD = (By.NAME, "email")
    PASSWORD_FIELD = (By.NAME, "password")
    CONFIRM_PASSWORD_FIELD = (By.NAME, "submitPassword")
    ERROR_TEXT = (By.CLASS_NAME, 'input_span__yWPqB')
    ERROR_BORDER = (By.CLASS_NAME, 'input_inputError__fLUP9')
    EMAIL_CONTAINER = (By.XPATH, "//input[@name='email']/ancestor::div[contains(@class, 'input_inputError__fLUP9')]")
    PASSWORD_CONTAINER = (By.XPATH, "//input[@name='password']/ancestor::div[contains(@class, 'input_inputError__fLUP9')]")
    CONFIRM_PASSWORD_CONTAINER = (By.XPATH, "//input[@name='submitPassword']/ancestor::div[contains(@class, 'input_inputError__fLUP9')]")
    USER_TEXT = (By.XPATH, "//h3[text()='User.']")
    USER_AVATAR = (By.CLASS_NAME, 'svgSmall')
    CREATE_AD_BUTTON = (By.XPATH, "//button[text()='Разместить объявление']")
    AUTH_REQUIRED_TEXT = (By.XPATH, "//h1[text()='Чтобы разместить объявление, авторизуйтесь']")
    AD_NAME_FIELD = (By.NAME, "name")
    AD_DESCRIPTION_FIELD = (By.XPATH, "//textarea[@class='textarea_inputStandart__IoNxq spanGlobal']")
    AD_PRICE_FIELD = (By.NAME, "price")
    CATEGORY_DROPDOWN = (By.XPATH, "//button[@class='dropDownMenu_arrowDown__pfGL1 dropDownMenu_noDefault__wSKsP']")
    CATEGORY_OPTION = (By.XPATH, "//button[@class='dropDownMenu_btn__o8ARs dropDownMenu_noDefault__wSKsP']")
    CONDITION_RADIO = (By.CLASS_NAME, "radioUnput_shell__Wtdwe")
    CITY_DROPDOWN = (By.XPATH, "//input[@name='city']/following-sibling::button")
    CITY_OPTION = (By.XPATH, "//button/span[text()='Москва']/parent::button")
    PUBLISH_BUTTON = (By.XPATH, "//button[text()='Опубликовать']")
    USER_PROFILE_BUTTON = (By.XPATH, '//button[@class="circleSmall"]')
    MY_ADS_SECTION = (By.CLASS_NAME, "profile_profile__bixlA")
    AD_ITEM = (By.CLASS_NAME, 'picture')
    INPUT_SEARCH = (By.XPATH, "//input[@placeholder='Я хочу купить...']")
